language: python
python:
 - 2.7
 - 3.3
sudo: false
install:
 - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b
 - export PATH=/home/travis/miniconda/bin:${PATH}
 - conda update --yes conda
 - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
 - conda install --yes -c dan_blanchard python-coveralls coverage
 - pip install -e .[test]
script: coverage run --source="artificialintelligence" setup.py test
after_success: coveralls
